id = "beejs"
name = "Beejs"
description = "Launches Beejs `bee lsp` for JavaScript, TypeScript, and .beejs files."
version = "1.9.1"
schema_version = 1
authors = ["Henry Zhang <hello@zhanghe.dev>"]
repository = "https://github.com/zh30/beejs"

[language_servers.bee-lsp]
name = "Beejs LSP"
languages = ["JavaScript", "TypeScript", "TSX", "JSX", "Beejs"]
language_ids = { JavaScript = "javascript", TypeScript = "typescript", TSX = "typescriptreact", JSX = "javascriptreact", Beejs = "beejs" }
