PackageIdentifier: zh30.bee
PackageVersion: 1.9.1
PackageName: Beejs
Publisher: Henry Zhang
License: MIT
ShortDescription: JavaScript/TypeScript runtime built with Rust and V8
PackageUrl: https://github.com/zh30/beejs
InstallerType: zip
Installers:
  - Architecture: x64
    InstallerUrl: https://github.com/zh30/beejs/releases/download/v1.9.1/bee-v1.9.1-x86_64-pc-windows-msvc.zip
    InstallerSha256: 0000000000000000000000000000000000000000000000000000000000000000
    NestedInstallerType: portable
    NestedInstallerFiles:
      - RelativeFilePath: bee.exe
        PortableCommandAlias: bee
ManifestType: singleton
ManifestVersion: 1.6.0
