{{- if and .Values.monitoring.enabled .Values.monitoring.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "beejs.fullname" . }}
  labels:
    {{- include "beejs.labels" . | nindent 4 }}
    {{- include "beejs.component" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "beejs.selectorLabels" . | nindent 6 }}
  endpoints:
    - port: http
      path: {{ .Values.monitoring.serviceMonitor.path }}
      interval: {{ .Values.monitoring.serviceMonitor.interval }}
      scheme: http
      {{- if .Values.monitoring.serviceMonitor.scrapeTimeout }}
      scrapeTimeout: {{ .Values.monitoring.serviceMonitor.scrapeTimeout }}
      {{- end }}
{{- end }}
