name = "beejs-website"
main = ".output/server/index.mjs"
compatibility_date = "2024-11-01"

[site]
bucket = ".output/public"

[build]
command = "npm run build"
watch_dir = "app"

[env.production]
vars = { NODE_VERSION = "20" }
